name: Docs

on: [push, release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install doc deps 
      run: |
        pip install .[docs]
    - name: Build notebooks for the docs
      run: |
        jupytext --to ipynb --execute docs/tutorials/*.py
    - uses: actions/upload-artifact@v2
      with:
        name: notebooks-for-${{ github.sha }}
        path: docs/tutorials
    - name: Trigger RTDs build
      uses: dfm/rtds-action@v1
      with:
        webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
        webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
        commit_ref: ${{ github.ref }}